### ISSUE TITLE
Add Automatic Name and Implement Automatic Saving

### ISSUE THREAD

**Issue by mariobehling** [fossasia/badgeyay#1427]
Please implement the following:

1. Until the user has given the badge a name, please assign an automatic name "Untitled Draft -1" or similar. Ensure there is no issue with storing docs and assign automatically a number if a previous name is taken.
2. Implement "Automatic Saving" and show the status "Saving" or "All changes saved" on top of the document similar to Google docs.

**Comment by ParthS007** [comment]
Google Doc is using sockets which remains active every time and update the name instantly on change. but since our backend API is deployed on Heroku and its dynos remain active only if a request is made so it is not possible to implement Automatic name saving on change instantly as we have to send a request to the backend to change it.

**Comment by ParthS007** [comment]
Completed, Hence closing :+1:
