### ISSUE TITLE
Preview section overlaps with footer links

### ISSUE THREAD

**Issue by YogeshSharma0201** [fossasia/badgeyay#1828]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

Preview section overlaps with footer links, when page is scrolled down to bottom.

![screenshot from 2018-10-17 12-00-45](https://user-images.githubusercontent.com/21025052/47151977-f80b1b80-d2f8-11e8-814e-5ced834d227a.png)

**Comment by RMPR** [comment]
Hello, i'm on this issue, give you feedback asap

**Comment by rupav** [comment]
@RMPR @YogeshSharma0201 are you working on this? Please update. I would like to work on this.

**Comment by RMPR** [comment]
Yes, I'm working on this

Le mer. 24 oct. 2018 à 09:04, rupav jain <notifications@github.com> a
écrit :

**Comment by RMPR** [comment]
yes, I tried several things, including modification of z-index, margin and
padding on containers,  but it seems like ember.js is responsible for this
issue, since I don't know ember, i leave this issue up to you, but when
you'll finish this, I would like to know how you did to solve it.
Regards

Le lun. 5 nov. 2018 à 22:25, Raj Vaibhav Dubey <notifications@github.com> a
écrit :

**Comment by rajvaibhavdubey** [comment]
Sure thing pal 👍

**Comment by sk9331657** [comment]
I am working on it now.
