### ISSUE TITLE
Create SVG-background (Inkscape+SVG editing issue)

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/badgeyay#20]
![](https://github.com/fossasia/badgeyay/raw/development/exhibitor.png)
The images like this have the following properties:

1. They have a **fix** color
2. They have a marker like "EXHIBITOR" written on them.

I would like to have my own text on thie beautiful background but with my own color.

**Possible Solution:**

Create an SVG file without the exhibitor text.
The triangles all have one color e.g. `#33ee66`, so that I can replace the color with find and replace in this SVG file. To change the brightness, you can add a grey triange above them. You can make it totally black and just change the transparency value.
You can use  [Inkscape](http://inkscape.org/) to create the file.

**Comment by amitsin6h** [comment]
let me take this as my first contribution.

**Comment by rupav** [comment]
@niccokunzmann 
I would like to work on this.

**Comment by niccokunzmann** [comment]
@rupav Sure, welcome! If you need anything, please let us know. Also, if you created a prototype instead fo an allaround perfect 100% forever solution, please also let us know :)

**Comment by rupav** [comment]
@niccokunzmann  you were referring to this image. Right? Which 'document' are you referring to in your comment ?
[(https://github.com/fossasia/badgeyay/blob/development/app/static/uploads/exhibitor.png?raw=true)]

**Comment by niccokunzmann** [comment]
@rupav Thanks, yes, this is the image. I changed "document" to SVG file because that is what I mean.

**Comment by rupav** [comment]
@niccokunzmann 
One last ques. 
As I earlier talked on gitter channel about this issue,I came to know that this is not codebase related issue.
So you basically want to get svg file created on Inkspace with your given requirements? I will work on this. :)

**Comment by niccokunzmann** [comment]
So "not codebase" means, that you do not need to setup the project, write python code, ...
So, in this issue you can focus on the basics: create a contribution, create a pull-request, get it approved.

**Comment by rupav** [comment]
Hi @niccokunzmann , I want to share my progress and need a suggestion:
![2017-09-20](https://user-images.githubusercontent.com/20624380/30628576-c8e16498-9df4-11e7-9ab3-3e0dd689401f.png)

So i created this abstract background( quite similar to the required one using 'voronoi diagram'). Now Here I have used 'pick color from layer 1' to color all the triangles, due to which all triangles are **Seperable or Ungrouped Entities/Objects**. Now if I want to change the color to say 'Orange', I will have to change the '**Fill** as can be seen in XML text editor' for all the objects/triangles. 

Can you please explain your Possible Solution in the root comment of this issue :).

Does your suggestion mean this :
Is there a way around if I can make all triangles 'Fill' parameter with some variable. Only opacity/alpha factor will then just make the required background i.e. We will just need to change this variable in 'XML file/ SVG file' and everything will fall in place?

**Comment by rupav** [comment]
Got the idea :), will submit my PR ASAP.
