### ISSUE TITLE
#2093 breaks frontend homepage

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/badgeyay#2111]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Description :**

#2093 breaks the frontend home page on npm 5.6.x

**Current behaviour:**

#2093 breaks the frontend home page on npm 5.6.x

**Expected behaviour:**

It doesn't effect the frontend

**Steps to reproduce:**
Deploy the frontend

**Screenshots**

![Screenshot from 2019-08-20 21-02-56](https://user-images.githubusercontent.com/8947010/63361629-195fec80-c38e-11e9-9cac-d010485023c1.png)

**Would you like to work on the issue?**

Yes

**Comment by abishekvashok** [comment]
Reverting #2093

**Comment by kushthedude** [comment]
Please find the root of problem, how can a pr break anything in which only semantic ui classes are changed . Let me tell you what broke it:
- You are still using updated dependancies and npm version on local.
- I told you about 2-3 times its not this easy to jump from ember 1.0 to 3.0, many of the dependancies are obsolete and code changes are there which need to be solved manually.
- If #2093 has caused it, please state the root cause and solve it in a PR , reverting it is not solutio. Reverting PR only works when in case something is broke or build is failing due to improper review .
Thanks

**Comment by abishekvashok** [comment]
> You are still using updated dependancies and npm version on local.

Nope, using local ones, I can switch versions using nvm
