### ISSUE TITLE
Deployment on AWS

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/badgeyay#222]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

Till now the project can be deployed only on Docker and Heroku

**Expected behavior:**

Branch out deployment into AWS

**Comment by meets2tarun** [comment]
@alirizwi 
Go Ahead

**Comment by yashLadha** [comment]
Should it be auto deployment or Deployment instructions

**Comment by meets2tarun** [comment]
Both

**Comment by raju249** [comment]
Is anyone working on this issue ?

**Comment by raju249** [comment]
I have been using AWS for a while now, so would like to take this up.

**Comment by yashLadha** [comment]
Yes, I am working on this issue. 😅

**Comment by raju249** [comment]
Hey @yashLadha 
No problem. :smile: 
May I know how are you thinking to deploy to AWS ?

**Comment by raju249** [comment]
Claiming this issue since @yashLadha is working on #374

**Comment by meets2tarun** [comment]
@raju249 Would you please tell your approach to proceed to solve this issue?
@yashLadha You can also post your work and the problem you faced while solving the issue.

**Comment by raju249** [comment]
Yes @meets2tarun .
Since we use just a server that runs our python code and nothing like nginx or apache, I was thinking of using Elastic beanstalk for this purpose. We can automate this and also provide instructions on how we can do it manually (They are just few command line commands using aws eb cli ).

For doing this we would require AWS account which will offer free tier of 1 year. 
But as @vaibhavsingh97 suggested in gitter channel, we should all focus on solving current issues that are blocking the forward movement of badgeyay. This issue is just a good feature to have but nothing is blocked due to this.

Let me know what you think :smile:

**Comment by yashLadha** [comment]
I researched of usng code deploy tool. But i wasn't able to find a one
click deployment tool for the EC2. I have been busy with the exams, so
wasn't able to do more.

**Comment by raju249** [comment]
I think I can work out one click deploy on AWS.
Will need to check.
