### ISSUE TITLE
Badges not generating from Manual data entry 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#314]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
pdf is not generating after giving input.

**Expected behavior:**
badges should be generated.

**Steps to reproduce:**
Enter data manually and generate pdf.

**Comment by gabru-md** [comment]
![img-20171103-wa0014](https://user-images.githubusercontent.com/25414121/32390862-12bdcde4-c0f6-11e7-8b93-39a2c2d0ddf6.jpg)

This is the issue log. I'll be reverse engineering the backend to find the issue that is causing this bug and will keep on sharing my progress on this.

**Comment by gabru-md** [comment]
@vaibhavsingh97 please see.

**Comment by vaibhavsingh97** [comment]
@ParthS007 @gabru-md Actually, the error is not because of manual entry. So if you enter manual data, and upload PNG then badge will be successfully generated but if you enter data manually and select image from dropdown than you can reproduce the error. The error because of wrong mapping i guess, Will look it tomorrow
