### ISSUE TITLE
Remove irrelevant data from Backend README.md

### ISSUE THREAD

**Issue by S2606** [fossasia/badgeyay#499]
@**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
Unnecessary data shown in backend readme.md file

**Expected behavior:**
Should be removed

**Steps to reproduce:**

**Comment by vaibhavsingh97** [comment]
@S2606 let's open this issue for beginners

**Comment by ParthS007** [comment]
@S2606 @vaibhavsingh97 @abishekvashok  Create a check list of the files to be removed from `backend` .It will be easy for begginner to follow up from there.

**Comment by sctsui** [comment]
@S2606 @vaibhavsingh97 I'm at a hackathon right now and I wanted to try doing some open source. If you make the check list for files to be removed, I would like to help. This is my first time contributing, so I hope you don't mind if I ask q's along the way! Thanks.

**Comment by vaibhavsingh97** [comment]
Sure, I will update this issue. Thanks

**Comment by raju249** [comment]
@sctsui Your questions are encouraged.
Welcome to FOSSASIA :smile:

**Comment by abishekvashok** [comment]
@sctsui you need to change the readme.md in backend and remove any unwanted docs which are not specific to the backend from it.

**Comment by yashLadha** [comment]
Are you still working on this @S2606

**Comment by Parag09** [comment]
i want to help fixing this issue. I cant find the checklist for the irrelevant data .. plz help I am new to open source

**Comment by ParthS007** [comment]
@S2606 @vaibhavsingh97 @abishekvashok @yashLadha  Please create a checklist of the files which are to be removed 👍

**Comment by abishekvashok** [comment]
It's not the files but irrevalend data in backend/Readme.md that needs to be removed.

**Comment by yashLadha** [comment]
I think all the README (Except installation README) needs to be updated according to the new project structure.

**Comment by rupav** [comment]
** To be done **:
- 3rd point needs to be modified in `introduction` [section](https://github.com/fossasia/badgeyay/tree/development/backend#badgeyay-backend) as now user have to enter 5 entries, instead of earlier 4.
- Remove `Usage`  [section](https://github.com/fossasia/badgeyay/tree/development/backend#usage), since Vagrant setup is available now. User Input Guide is not required either now.
- Fix `installation` [links](https://github.com/fossasia/badgeyay/tree/development/backend#installation) to correct location.
- Fix `implementation` [links](https://github.com/fossasia/badgeyay/tree/development/backend#implementation) to correct location.
- Fix a [link](https://github.com/fossasia/badgeyay/tree/development/backend#maintainers) in `maintainers section` with text `Badgeyay`.

I would like to claim it if no beginner takes up the issue in coming few days. If its fine for you guys @yashLadha @vaibhavsingh97  @raju249 @S2606 @abishekvashok @ParthS007 ?

**Comment by abishekvashok** [comment]
Yea it looks good. @rupav

**Comment by yashLadha** [comment]
:+1:  @rupav

**Comment by Minkush-sopho** [comment]
@rupav Can I take up this issue?

**Comment by rupav** [comment]
@Minkush-sopho yes, go ahead 👍

**Comment by Minkush-sopho** [comment]
@rupav  ok sir

**Comment by rupav** [comment]
@Minkush-sopho no "sir" please 😅

**Comment by Minkush-sopho** [comment]
@rupav  ohk :)

**Comment by Minkush-sopho** [comment]
@rupav  Can you please suggest what needs to be added as the 5th field in introduction section's 3rd point?

**Comment by rupav** [comment]
@Minkush-sopho as per https://github.com/fossasia/badgeyay/pull/476 it should be `Designation` field.

**Comment by Minkush-sopho** [comment]
@rupav thanks 👍

**Comment by Minkush-sopho** [comment]
@rupav  please review https://github.com/fossasia/badgeyay/pull/542
