### ISSUE TITLE
Footer overlaping when Failure message show

### ISSUE THREAD

**Issue by avsingh999** [fossasia/badgeyay#626]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

when we fill wrong data then failure message show like this
![overl](https://user-images.githubusercontent.com/25536022/38684517-8271065a-3e8d-11e8-8a9f-4778e840b9f8.PNG)

**Expected behavior:**
footer and failure message should not overlap.

**Comment by sagar-kalra** [comment]
![screenshot_20180413_132648](https://user-images.githubusercontent.com/31239108/38723347-660f1934-3f1e-11e8-9c0f-1caf97513a47.png)
It is working fine for me

**Comment by avsingh999** [comment]
@sagar-kalra  but not in my browser or laptop

**Comment by sagar-kalra** [comment]
Which browser are you using?
P.S.: I have tried Firefox and Chrome.

**Comment by avsingh999** [comment]
@sagar-kalra  I have also checked both browser

**Comment by prmsrswt** [comment]
The problem lies in the screen size if it is a 720p display then due to scaling the error message hides behind the footer. 
![screenshot from 2018-04-14 00-43-34](https://user-images.githubusercontent.com/29674758/38753866-60db28cc-3f7d-11e8-8cfe-b2360af577dc.png)
I can think two ways of resolving this issue:
- The footer is fixed at bottom, if we remove the `position: fixed;` for #footer in css/style.css then the issue will be solved.
- We can use a empty division with a fixed hieght of 20px (footer's height) before the footer using html code `<div style="height: 20px;"></div>`.

As I am new to open source I don't know much about contributing, so I am unable to decide what to do next, any help will be appreciated.

**Comment by vaibhavsingh97** [comment]
claiming 👍

**Comment by vddesai1998** [comment]
I would like to work on this issue.Can someone assign me the issue?

**Comment by gabru-md** [comment]
@vddesai1998 I do not know if you can be assigned to this issue, since GSoC is currently under way.
@djmgit @ParthS007 please comment

**Comment by vddesai1998** [comment]
@gabru-md so what should I do if I want to start contributing...? Are there any non GSoC issues?

**Comment by gabru-md** [comment]
I do not have any idea regarding it. I have tagged a mentor (@djmgit) so that he can clarify the situation.
:sweat_smile:

**Comment by vddesai1998** [comment]
@gabru-md Thanks!

**Comment by djmgit** [comment]
@vddesai1998 please have a look at my comment on badgeyay channel in gitter :)
Welcome to badgeyay :)
