### ISSUE TITLE
Refactoring frontend

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#629]
Presently the entire frontend comprises of two huge files : application.hbs and index.hbs which should not be the case at all. We need to distribute the app into components, which is the prefered workflow in emberjs. This will make the codebase much more easily maintainable and clean. 
For example, we can create a component for the menu, a component for the central box, a component for 'choose your background section', one for 'choose data source' etc.
Also presently we are interacting with backend API via jquery Ajax which is again not the prefered way in emberjs. We need to use ember data and ember models for this. As of now the codebase is yet not that big. So I guess this the right time to refactor the code.

**Comment by ParthS007** [comment]
Yes, I agree with you on this @djmgit, We can discuss it as @gabru-md  said, with you on how to proceed with this. We can make a checklist according to priority and start working on this part as well as for the backend part. :)

**Comment by vaibhavsingh97** [comment]
Agreed with you @djmgit 👍

**Comment by yashLadha** [comment]
Why not create an issue showing the components in a bulleted format. It would be better to visualize and easy to assign to work. @djmgit

**Comment by djmgit** [comment]
@yashLadha yes we can definitely do that. Once we are sure of the components, I can edit and modify this issue itself. We can discuss what components we require here itself :)

**Comment by ParthS007** [comment]
@djmgit I will share a basic tree structure of components, adapters, services, routers on which I will start working in order to refactor frontend. :+1:

**Comment by yashLadha** [comment]
I have started working on creating models and controller for form submission. May be we both can work on it. Also ref #698 is also connected with the same issue for adding a JSON API Adapter in the form. @ParthS007

**Comment by vaibhavsingh97** [comment]
I will also help in refactoring frontend

**Comment by gabru-md** [comment]
Since everyone is working on this part, it seems that tge csv upload issue is now open for me ?  So I'll work on it then

**Comment by gabru-md** [comment]
My whole point is that you are working on multiple issues right now, which according to your point of 'group project' is also not okay.

I've already stated that I mentioned it in my scrums before you created the issue. I have my exams so I did not open up github to create any issue, considering I can create it when I am done with my studying, because of the fact that I've stated ot before anyone else.

But since it is a `group project` and I being a member of this group isn't assigned to any issue whereas you are assigned to multiple, you should let me have it. :+1:

**Comment by gabru-md** [comment]
And from now on I'll make sure that this never happens and I have an issue ready as soon as I write it down somewhere in my scrums :+1: :)

**Comment by vaibhavsingh97** [comment]
@gabru-md According to policy, one should open issues first and claim it. Nobody has time to read scrums, scrums are only to log your work to keep track of the progress made so far. In GitHub there is a reason `issue` tab exist, please make use of that. Also, it's ok if your exams is going on than you can ask fellow developer to help you. Right now what I am seeing is that rather than a group project, it's a single person project.

**Comment by yashLadha** [comment]
It is this that the REST API issue cannot be work currently as it needs
models in frontend, so technically it is same as like socket issue because
we first need to finish higher priority issues first and then work. So
technically I am now not assigned to any issues. Hope you understand that
ember normally not handles the input very well. So working on the work
around @gabru-md. It's good with me that if you want to claim the issue.
GFI cheers.

**Comment by djmgit** [comment]
@vaibhavsingh97 @ParthS007 @gabru-md @yashhere lets try to avoid conflicts on issues and features. @gabru-md and @ParthS007 mentioned earlier that they will be working on creating the refactored API, and its already going on at a nice pace. The API has already got a nice structure :+1: @yashLadha your were working on refactoring the current application logic cleaning it up, you have already sent some PRs regarding that, which is good. I guess soon @gabru-md and @ParthS007 will be able to integrate it with the new API structure.

So what I mentioned above is the ```current workflow``` that I am aware of till now. However I see a lot of conflicts right now which might affect the project as a whole. Since 4 people are working on this project, such conflicts can occur and lets not get upset with these issues. GSoC coding period is going to start soon and  lets keep the project going smoothly. So what I was thinking of are as follows:

Lets come up with a excel sheet or google doc latest by 11th (start of coding period). You guys discuss among yourselves, on which part who wants to work. So that everyone is aware about who is doing what, and no conflicts occur, or even if it occurs then it can be resolved easily.
Please do not take up multiple issues at a time, keep an upper limit of two, send PR, get them merged and then move to your next work.(Well, a critical PR might take a long time to be get merged in that case you can keep working on other tasks).
During the coding period, after creating a issue ```please comment``` if you are willing to work on that issue, so that no one else work on it. A comment is enough to make others understand that work is already going on, on that issue.

Lets try to avoid such conflicts during the coding period and make this project a success.

**Comment by ParthS007** [comment]
@djmgit I completely agree with you. So, let's do it.
1. Link to Badgeyay Backlog 2018 - [Link](https://docs.google.com/spreadsheets/d/1pqWOqBc7wprsCZFYBXEqx620mMg4LwCtncTw6NeQi0k/edit?usp=sharing)
2. Link to Work Division - [Link](https://docs.google.com/document/d/1wMDZfkQlTRCkTD5OHKvsn1WBttfy3AlViw9jWTkK-9E/edit?usp=sharing)
I have created the second one. and let's start working on completing this to avoid conflicts. :smiley: 

Regarding this issue - 
@djmgit @yashLadha @gabru-md @vaibhavsingh97 ok, let's finalize a tree structure so that we all can start working on implementing it where everyone can claim their part. I am here referring to frontend only.
I hope everyone is agreed with it.

PS: Request Edit access for editing the Work Divison Doc :smiley:

**Comment by vaibhavsingh97** [comment]
@ParthS007 That's quick, appreciated you created the doc but this would create a  mess in near future once we progress in the project so there are third party plugins which help you manage the `group project` with the help if GitHub. We can take help of these plugins or excel sheet be the best case to manage these type of things. 
@ParthS007 views?

**Comment by gabru-md** [comment]
@vaibhavsingh97 I guess you are wrongly notified here.
Scrums are an important part of GSoC and mentors and admins get knowledge about our work from scrums only. Therefore your point that nobody reads scrum, is not okay. It is completely wrong. 
@djmgit am I right ?
