### ISSUE TITLE
Sending the form data using socket connection

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#666]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Currently the server is configured for cors requests and an AJAX call is made to the api but the flask-scoketio library and flask-cors have conflicts in the cors functionality. So it is better to use on library and to not have conflicts in the cors. SO instead of sending data using AJAX, the form data should be send using socket.
__I am working on this__

**Comment by gabru-md** [comment]
I am sorry, but we will be using `ember-data` to send data from front-end to back-end server.
It is far more better than using Sockets for sending information. 
Handling sockets will not be a good idea for sending sensitive form data even in case of logins and signups. 
I do not approve of using socket for the same.

@djmgit @ParthS007 please comment. Since there are services already available for us that help in `data` services. I guess this issue is redundant. :/

**Comment by yashLadha** [comment]
@gabru-md  This is inspired from the issue https://github.com/fossasia/badgeyay/issues/594 and in openevent project also the use of sockets are supplied to send the data from frontend to backend. Also the same code can be extended for the issue.

**Comment by ParthS007** [comment]
@yashLadha I don't understand when we are using Ember framework in which there is proper method to handle data i.e ember-data and we have to divide index.hbs in multiple components which is main motive to use a frontend framework. I don't think this PR will be of any use now as we have to again change it according to Components.

**Comment by yashLadha** [comment]
I am closing this issue as the writing test for socket communication will be using selenium and for the task may be we can drop the idea but the ember-data provides us way to handle the data with ember but sockets are reliable and fast way of communication when we need to send small packets of data. In the ember forum there are discussion on using both `ember-data` and `sockets` for a reliable communication. Sure @ParthS007 , may be later we can intact the communication with the sockets and ember-data both.

**Comment by djmgit** [comment]
@gabru-md @yashLadha @ParthS007 #594 demands inclusion of a progressing loading bar. As it was discussed in #594 earlier that we have two ways to display progress bar. Either some how continuously poll the number of badges generated using ajax or use socket.io and flask socket for reactive communication. It was decided that sockets will be used for the progress bar. However since we are using ember we need to find a proper way of integrating ember with socket. lets see if we can find a ember-socket node module!
However lets address this issue after some time. I guess the most important task write now is api refactoring and frontend refactoring. Once GSoC work period starts, you all will be working on your respective tasks, and at that time refactoring will be a real pain. So lets get done with it as soon as possible. We can always come back to this issue afterwards.

**Comment by yashLadha** [comment]
Sure @djmgit :+1:
