### ISSUE TITLE
Addition of documentation to Response class

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#679]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Parent Issue : https://github.com/fossasia/badgeyay/issues/627
__I am working on this__

**Comment by yashLadha** [comment]
CC : @djmgit

**Comment by gabru-md** [comment]
@yashLadha Actually the class has been made to comply with these changes.

**Comment by gabru-md** [comment]
You can use 
`Response(403)generateMessage('Not authorized')`
to achieve the same.

**Comment by yashLadha** [comment]
Now is it comfortable with you @gabru-md

**Comment by gabru-md** [comment]
There will be several changes to the backend so I feel we should have @djmgit comment her for the same.
Because it may happen that we may extend functions onto functions and even change some. So lets move onto the documentation part at last?

Like we can have this as the parent issue so that we keep on adding the functionalities that have been done so that we can work on documentation after that, like once a functionality or class is done and requires no change then documentation can be done ? What are your views @yashLadha

**Comment by yashLadha** [comment]
According to me adding documentation to the code which we are adding gives
and understanding what we are doing to implement. Also it is a good
practice to add documentation of whatever code we right.

**Comment by ParthS007** [comment]
closing this :+1:
