### ISSUE TITLE
CSV Upload API

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#701]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Endpoint to upload CSV file.

__I am working on this__ Will send PR after #697 gets merged.

**Comment by gabru-md** [comment]
I am sorry, but I have written about working on the same in my daily scrums before you created this issue. moreover you have already been working on an issue that you created yourself [#698](https://github.com/fossasia/badgeyay/issues/698).  Isn't that a bit unfair if you claim issues that others have already mentioned in their scrums that they will be working on ?

@djmgit can you please resolve my doubt of who should be working on it ? :confused:

**Comment by yashLadha** [comment]
Ther is no issue created in the repository so I thought that no one has claimed. If you are going to work on the issue then you should create that in the first place and if you have created the issue and claimed it then I have no problem with that. Also, ref #698 the structure of the form is not yet finalized and if the model structure is yet to decide on frontend side.  @gabru-md

**Comment by gabru-md** [comment]
Since you are working on issue for frontend it seems apt that I can now claim this issue, considering the fact that I, unlike you, have no issue claimed at this moment. 
Whereas you've stated in the comments of frontend issue that you're working on modelling etc.

Therefore I can now work on this issue.
