### ISSUE TITLE
API Endpoint to change user details

### ISSUE THREAD

**Issue by yashLadha** [fossasia/badgeyay#709]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There is no endpoint to serve updation of user details like password or name.
**Expected behavior:**
There should be an endpoint to serve the purpose.

__Yes__ I am sending PR for the same.

**Comment by vaibhavsingh97** [comment]
Are we going to add handle \ authentication, registration, account management manually?  Instead, we can use some third-party plugin or can use a cloud-based solution like Firebase, etc. We can focus on providing badges as a functionality.
Cc @djmgit @yashLadha @ParthS007 @gabru-md your Views please

**Comment by yashLadha** [comment]
See @vaibhavsingh97 we can definitely move to PaaS like Firebase but we will only be using admin sdk on server side and thus the logic will not be different it is just some parts of code will be using the sdk functions. Like Firebase SDK Provide a method to update user details but for updating the user it must have to be a valid user at first place. Also after validation from firebase server we can move to just altering the dict and sending the dict to server for user updation. It is just that at first place basic API should be done and them at later stage we can integrate the Firebase SDK.

**Comment by gabru-md** [comment]
It has already been done.
It was discussed in the meeting that if we can get the simple authentication done earlier then we will prefer it doing ourself and if not, the Yash ladha said he would work on firebase part. 
But since basic authentication has already been setup therefore I don't think we need firebase as of now.
As Yash said, we will be hardly using some functions of the sdk. So we can leave it for now.
