### ISSUE TITLE
Discussion on database service

### ISSUE THREAD

**Issue by djmgit** [fossasia/badgeyay#764]
Since we are integrating Firebase with badgeyay, the question is should we stick to our own database (Postgres) or should be go for firebase data store? What is the most suitable option for badgeyay?

**Comment by djmgit** [comment]
@ParthS007 @vaibhavsingh97 @gabru-md @yashLadha what are your views?

**Comment by yashLadha** [comment]
See Firebase Firestore provides query feature but it is not as powerful as the RDMS like PSQL and also there is a factor of network latency in it. So I think we can have both the structures in place and work.

**Comment by yashLadha** [comment]
Also firebase storage and database are in place whenever we create our app. So it will be better to create models and the schema structure for the database. @djmgit Like how the queries will be done from the firebase database because there is no iterator available in firebase storage so we have to maintain the details in the database itself.

**Comment by djmgit** [comment]
@yashLadha you right about the network latency issue. So @yashLadha @vaibhavsingh97 should we proceed with our native database? Flask goes will with Postgres and sqlalchemy, also it is a prefered stack. In that case I guess @vaibhavsingh97 can start with the schema for storing badges.

**Comment by yashLadha** [comment]
@djmgit , as it said in the previous meeting that we will need an option for such as external cloud storage and firebase, is an apt choice as we are using the authentication suite. But for the purpose of storing the details of media assets we have to use PSQL as it will be more powerful and the database schema that is used in firebase is NOSQL so we have to again re-write the schema to fit with the NOSQL database. The approach for using the firebase storage would be like as follows:

* Upload the file to storage bucker
* Retrieve the metadata for the uploaded file.
* Store the details in the PSQL database
* Use the details later to retrieve the file from the storage.

For the authentication, part firebase will only give us ease to register user and validate them but to manage the roles as pointed by @gabru-md have to be done by us using the PSQL. 

Views on the approach @djmgit @vaibhavsingh97 @ParthS007 @gabru-md

**Comment by vaibhavsingh97** [comment]
@djmgit I agree with @yashLadha as we are storing configs, details of media assets we have to use PSQl because of it's performance and the database used by firebase is NOSQL, and we have to rewrite the database schema to store assets. As we are using PSQL databse either we can stick with local database or Cloud Database. So as pointed by @mariobehling in meeting, that what if we get thousands of user and requesting to genrate badges. We will need databse service which can scale up and down. We can then use **AWS RDS** or **Cloud SQL** by GCP. I am with **AWS RDS**, as it's used by industry and better support in terms of documentation and developement.

![mydiagram](https://user-images.githubusercontent.com/8705386/40039106-aa2dc5fc-5832-11e8-8e7a-87e1a1493700.png)

I had architected small solution using AWS RDS, I have only considereed the scenario of storing and retriving assets.

_**Free tier of AWS RDS**_  (750 Hours per month of db.t2.micro database) [We will not exceed extra hours]
**Benefits of RDS**:
- Easy to Administer
- Highly Scalable (We don't have to care about scalibility, Amazon takes care of that. We have to only focus on developemnt)
- Fast and Secure

Also, to store genrated badges we can make uses of AWS S3 (Simple Storage Service)
![mydiagram 1](https://user-images.githubusercontent.com/8705386/40040074-64bacf0c-5836-11e8-8136-16eba4fc983c.png)
This diagram, shows how can we store badges in S3 bucket. It's an Object Based Storage, so we can store any file like text, songs, movies, pdfs, etc. So as @gabru-md had said, we don't have to store the badges which are old, so S3 had an service which will schedule for deletion automaticaly after (`n` - No. of Days) described by user. So we can define Lifecycle management in the console itself, so it will be delted from the storage automatically after `n` days. Hence, saving storage.

_**Free tier of AWS S3**_ (5 GB of Amazon S3 standard storage, 20,000 Get Requests, and 2,000 Put Requests)
**Benefits of AWS S3**
- Durable and Scalable
- Data Archiving
- Can Help in Analytics (like number of badges genrated, number of drafts, etc)

_**Free tier of AWS SNS**_  (1,000,000 Requests, 100,000 HTTP notifications and 1,000 email notifications)
- Simple Pub/Sub messaging
![image](https://user-images.githubusercontent.com/8705386/40040454-f8771402-5837-11e8-9c25-d19a60122ec2.png)

**Explaination**: In Second, Diagram, User request to genarte a badge, User click on genrate badge button. A request goes to lambda function, it creates a unique ID in RDS and publish an event Notification to SNS and second Lambda function subscribe the notification, Badge genration happens and genrated badges stored in the S3 and url of the genrated badge is passes to the lambda function. Lmbda function store the genrated badge url in the RDS (User get's a notification that badge is genrated). User click on the link and redirected to the S3 bucket where the badge is stored.

Your views @djmgit @gabru-md @ParthS007 @yashLadha I just proposed the idea, if you don't like it, I am happy to accomodate changes suggested by you guys. Thanks

**Comment by ParthS007** [comment]
Cost wise GCP is cheaper than AWS and the options provided by AWS are extensive and won't be used for an application of the stage of badgeyay.
We can use cloud functions that act in a similar way as AWS Lambda functions. So we can say firebase is a complete suite for all needs except the database.
For that while in development we can use localhost and when in productions we will switch to cloud instances as this merely affects the schema and structure.

**Comment by vaibhavsingh97** [comment]
@yashLadha @ParthS007 We will not use Badgeyay on cloud completely. The architecture I proposed only to dump data in database and S3. Also, we only need Lambda as for an even cal as these services listen to events or you can directly call the API provided by the services. Yes, @ParthS007 you are right, we need international credit/debit card but why are we bound to this? We should simply think about merit/demerit of using the database on Local/AWS/GCP. Also, GCP is costly, as you can see [here](https://cloud.google.com/sql/pricing), they charge you whatever you use, in terms of network and instance use whereas AWS gives you all things for free and billed at 9.20$ per month if exceed the free tier limit otherwise it will be free. IMO, I don't think we are gonna exceed the free tier limit.

**Comment by yashLadha** [comment]
See @vaibhavsingh97 GCP does hourly billing whereas i don't think AWS has hourly billing. Secondly when we are using Firebase Storage why not use the full suite. There is no need to write lamdba function as cloud functions does a better job at listening tasks related to the complete suite of service wheter it is authentication, database or storage. Also GCP provided a 12000 Rs. free value for one year which is same as like AWS. We can clearly see the difference in price @vaibhavsingh97 
![image](https://user-images.githubusercontent.com/18033231/40044245-7763ba20-5844-11e8-8d67-7f26f95bb36e.png)

**Comment by yashLadha** [comment]
I think the thing you are saying @vaibhavsingh97 will be only be free for the free tier period and after that we have to follow the regular pricing [Link](https://aws.amazon.com/free/?awsf.default=categories%2312monthsfree)

**Comment by yashLadha** [comment]
Ok @vaibhavsingh97 but still the pricing you can see is far less as compared to AWS.

**Comment by yashLadha** [comment]
And the features I have already said. Can you provide a better proof? As you can see me and @ParthS007 are in favour of Firebase and the suite provided.

**Comment by gabru-md** [comment]
google cloud it is then ?

**Comment by djmgit** [comment]
@yashLadha @vaibhavsingh97 @ParthS007 @gabru-md if you guys are satisfied with GCP then please go forward with it. @vaibhavsingh97 once this is confirmed please get started with setting up the badgeyay db service ASAP :)

**Comment by djmgit** [comment]
@yashLadha @vaibhavsingh97 @gabru-md @gabru-md whats the status of this? @vaibhavsingh97 please update and start working on this.

**Comment by gabru-md** [comment]
@djmgit I don't know. It has been 3 days and there has been no update from Vaibhav on the same.
The issue has been stalling for now.
@ParthS007 @yashLadha do you have any idea?

**Comment by vaibhavsingh97** [comment]
@gabru-md @ParthS007 @yashLadha @djmgit Sending PR , and I will update my previous PR's

**Comment by gabru-md** [comment]
@vaibhavsingh97 please make changes to the previous PR that you've opened. 
There are a lot of problems with them. Instead of focusing on a new PR and stalling them all, I guess you should work on making the already created ones work.

**Comment by yashLadha** [comment]
@vaibhavsingh97 it seems you haven't read the guidelines said by @djmgit. Please either update your current PRs or close them. Is it right or not @ParthS007 @gabru-md

**Comment by ParthS007** [comment]
We are going with **Google cloud Postgres Instance and Firebase Storage(For storing Media assets)**
Hence, This issue can be closed @djmgit  :+1:

**Comment by djmgit** [comment]
great :+1:
