### ISSUE TITLE
Updating REST Endpoints for User Signup for Firebase Admin

### ISSUE THREAD

**Issue by ParthS007** [fossasia/badgeyay#770]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Working on it**

**Comment by vaibhavsingh97** [comment]
@ParthS007 This issue is duplicate of https://github.com/fossasia/badgeyay/issues/707
Also, in this issue, i had shown interest in that issue and you also asked me to work on that and now you had deleted the comment.
Ref: ![image](https://user-images.githubusercontent.com/8705386/40195150-4ad117fe-5a2a-11e8-8533-3e3ecc5370e2.png)
