### ISSUE TITLE
using "pipenv" instead of virtualenv

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#849]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behaviour:**
Currently, `virtualenvironment` is used for creating the virtual environment where one can install dependencies and run the project. We have to maintain `requirements.txt` file to track the dependencies used in the project.

**Expected behaviour:**
One can use [`pipenv`](https://github.com/pypa/pipenv) to maintain dependencies for us. It automatically creates and manages a virtualenv for our projects, as well as adds/removes packages from your Pipfile as we install/uninstall packages. It also generates the ever-important Pipfile.lock just like nodejs

**Yes, I am working on this issue**

**Comment by gabru-md** [comment]
Isn't this an issue of personal choice?

**Comment by gabru-md** [comment]
We have virtualenv, vagarant and even docker.
Why are we adding a new thing, when everyone is comfortable with virtualenv ? And as I said before, if it is a personal choice then shouldn't it be done on the user's end? 
Please correct me if I am wrong

**Comment by yashLadha** [comment]
@vaibhavsingh97 pipenv doesn't gives all the dependencies that are needed by project as if some addon for the model is installed it won't be able to give and what is the problem with current virtualenv as it comfortable in working and on the point of requirements.txt as soon as one adds a dependency in the project one can add the same in requirements.txt and it's hardly job of couple of seconds instead of at the end doing `pip freeze`.

**Comment by yashLadha** [comment]
Yes and i agree with @gabru-md instead of working on such issues can you please help us in making the project stable as the latter will be more beneficial for us.

**Comment by ParthS007** [comment]
closing this as not needed :+1:
